### ISSUE TITLE
Missing `model_factors` help page

### ISSUE THREAD

**Issue by aitap** [JobNmadu/Dyn4cast#2]
You've mentioned on Mastodon that your `model_factors` help page is missing from various help indices, including the package website. This stems from `\keyword{internal}`:
https://github.com/JobNmadu/Dyn4cast/blob/509de482dd19e23abd3a3d597a2167c41d2a2013/man/Model_factors.Rd#L40
...caused by the roxygen2 tag here:
https://github.com/JobNmadu/Dyn4cast/blob/509de482dd19e23abd3a3d597a2167c41d2a2013/R/Model_factors.R#L42

**Comment by JobNmadu** [comment]
Thanks very much. I observed it but did not think it was the cause because
one other function had it and it was showing. It has now been demobilised.

Job N Nmadu. *God* can, you *come*!


Professor, Department of Agricultural Economics and Farm Management.


Dean, School of Agriculture and Agricultural Technology (2021-2023),

Federal University of Technology, Minna, Nigeria *(**www.futminna.edu.ng
<http://www.futminna.edu.ng/>**)*.


Industrial Liaison Officer (2019-2021)


Deputy Director, Quality Assurance and Productivity (2018-2019)


Head, Department of Agricultural Economics and Extension Technology
(February, 2008- November, 2012)

&


President (2017-2024) and Fellow, Nigerian Association of Agricultural
Economists (*www.naae.org.ng <http://www.naae.org.ng/>*)

*www.jobnmadu.com <http://www.jobnmadu.blogspot.com/>*
***@***.***

***@***.***
***@***.***>
